[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[project]
name = "mapfun"
version = "0.9.0"
authors = [
  { name="zakaria elalaoui", email="" },
]
description = "A function that applies a mapping function to an infinite number of input elements, with options to skip certain elements and selectively apply the mapping to keys and/or values of objects.e"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/zakarialaoui10/mapfun#python"
"Bug Tracker" = "https://github.com/zakarialaoui10/mapfun/issues"
