name: Node.js Package Test

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name : Find File
        run : cd ./Javascript
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm test
